[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
state = {path="../state"}
engine = {path="../engine"}

macroquad = "0.3.25"
